"""change structur trevels tabel

Revision ID: 603ecebdefab
Revises: fe9072d08b7b
Create Date: 2024-05-29 13:46:12.526941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '603ecebdefab'
down_revision: Union[str, None] = 'fe9072d08b7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('travels', sa.Column('user_travel_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'travels', 'users_travels', ['user_travel_id'], ['id'])
    op.drop_column('travels', 'title')
    op.drop_column('travels', 'img')
    op.drop_column('travels', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('travels', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('travels', sa.Column('img', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('travels', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'travels', type_='foreignkey')
    op.drop_column('travels', 'user_travel_id')
    # ### end Alembic commands ###
