"""Add index to status

Revision ID: 784d7016604c
Revises: 5fe99e132984
Create Date: 2024-05-28 01:47:56.013437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '784d7016604c'
down_revision: Union[str, None] = '5fe99e132984'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_friends', sa.Column('status', sa.Integer(), nullable=True))
    op.create_index('idx_status', 'user_friends', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_status', table_name='user_friends')
    op.drop_column('user_friends', 'status')
    # ### end Alembic commands ###
