"""Add index to status

Revision ID: fe9072d08b7b
Revises: a5df532dd16b
Create Date: 2024-05-28 16:56:28.379796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe9072d08b7b'
down_revision: Union[str, None] = 'a5df532dd16b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('mean_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('places', 'mean_score')
    # ### end Alembic commands ###
